config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :welcome, only: :index
  resources :assignments
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
# frozen_string_literal: true

class Assignment < ApplicationRecord
  belongs_to :user
  has_many :schedules, dependent: :destroy

  accepts_nested_attributes_for :schedules, allow_destroy: true

  before_create :format_dates

  validates :name, :start_date, :end_date, presence: true
  validate :start_date_constraint
  validate :date_constraint

  def options_for_select
    available_days.map { |date| [date.strftime('%A'), date.to_datetime] }
  end

  private

  def available_days
    return [] unless valid_dates?

    (start_date.to_date..end_date.to_date).to_a.map(&:to_date)
  end

  def format_dates
    self.start_date = start_date.beginning_of_day
    self.end_date = end_date.end_of_day
  end

  def start_date_constraint
    return unless valid_dates?

    errors.add(:start_date, 'must be greater than yesterday') if start_date < Time.current.beginning_of_day
  end

  def date_constraint
    return unless valid_dates?

    errors.add(:end_date, 'must be greater than the start date') if end_date < start_date
  end

  def valid_dates?
    start_date.present? && end_date.present?
  end
end

app/models/quotum.rb
# frozen_string_literal: true

class Quotum < ApplicationRecord
  belongs_to :schedule

  validates :q_hours, :q_minutes, :amount, presence: true
  validates :q_hours, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 24
  }
  validates :q_minutes, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 60
  }
  validates :amount, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  belongs_to :assignment
  has_many :quota, dependent: :destroy

  accepts_nested_attributes_for :quota, allow_destroy: true

  validates :scheduled_at, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable

  has_many :assignments

  validates :first_name, :last_name, :email, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_controller
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  def set_controller
    @controller = controller_name
  end
end

app/controllers/assignments_controller.rb
# frozen_string_literal: true

class AssignmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_assignment, only: %i[show edit update destroy]

  def index
    @assignments = current_user.assignments
  end

  def new
    @assignment = current_user.assignments.new
    @assignment.schedules.build.quota.build
  end

  def create
    @assignment = current_user.assignments.new(assignment_params)
    if @assignment.save
      redirect_to assignments_path, notice: 'Created successfully!'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @assignment.assign_attributes(assignment_params)
    if @assignment.save
      redirect_to assignments_path, notice: 'Updated successfully!'
    else
      render :edit
    end
  end

  def destroy
    if @assignment.user == current_user
      @assignment.destroy
      redirect_to assignments_path, notice: 'Deleted successfully!'
    else
      redirect_to assignments_path, notice: 'You must be the owner!'
    end
  end

  private

  def set_assignment
    @assignment = current_user.assignments.find_by(id: params[:id])
  end

  def assignment_params
    params.require(:assignment).permit(
      :name,
      :start_date,
      :end_date,
      schedules_attributes: [:id, :scheduled_at, :_destroy, quota_attributes: %i[
        id q_hours q_minutes amount _destroy
      ]]
    )
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/assignment_helper.rb
# frozen_string_literal: true

module AssignmentHelper
  def date_formatter(date)
    return '' unless date.is_a?(Time)

    date.strftime('%b %d, %Y')
  end

  def updated_at_formatter(date)
    return '' unless date.is_a?(Time)

    date.strftime('%b/%d/%Y - %H:%M')
  end
end

app/views/assignments/_card.html.erb
<div class="col mb-4">
  <div class="card h-100 text-center">
    <div class="card-body">
      <h4 class="card-title"><%= assignment.name %></h4>
      <p class="card-text"><%= "<strong>Start date:</strong> #{date_formatter(assignment.start_date)}".html_safe %></p>
      <p class="card-text"><%= "<strong>End date:</strong> #{date_formatter(assignment.end_date)}".html_safe %></p>
      <%= link_to 'Show', assignment_path(assignment), class: 'btn btn-sm btn-info' %>
      <%= link_to 'Edit', edit_assignment_path(assignment), class: 'btn btn-sm btn-secondary' %>
      <%= link_to 'Delete', assignment_path(assignment), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: 'Are you sure?'} %>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= "Last updated at #{updated_at_formatter(assignment.updated_at)}" %></small>
    </div>
  </div>
</div>

app/views/assignments/_form.html.erb
<%= form_for assignment do |f| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
        <% assignment.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', autofocus: true %>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= f.label :start_date %>
        <%= f.text_field :start_date, class: 'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= f.label :end_date %>
        <%= f.text_field :end_date, class: 'form-control' %>
      </div>
    </div>
  </div>

  <hr>

  <div class="schedules">
    <%= f.fields_for :schedules do |schedule_form| %>
      <%= render 'schedule_fields', f: schedule_form %>
    <% end %>
    <%= link_to_add_association 'Add schedule', f, :schedules, class: 'btn btn-sm btn-dark' %>
  </div>

  <hr>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", assignments_path, class: 'btn btn-secondary float-right' %>
  </div>

  <script type="text/javascript">
    $(function() {
      $('#assignment_start_date').daterangepicker({
        autoUpdateInput: false,
        opens: 'center',
        locale: {
          cancelLabel: 'Clear',
          format: 'DD/MM/YYYY'
        }
      });

      $('#assignment_start_date').on('apply.daterangepicker', function(ev, picker) {
        $(this).val(picker.startDate.format('DD/MM/YYYY'));
        $('#assignment_end_date').val(picker.endDate.format('DD/MM/YYYY'));

        var optionsForSelect = getDates(picker.startDate, picker.endDate);
        optionsForSelect.forEach(element => $("select").append("<option value='" + element[1] + "'>" + element[0] + "</option>"));
      });

      $('#assignment_start_date').on('cancel.daterangepicker', function(ev, picker) {
        $(this).val('');
        $('#assignment_end_date').val('');
      });
    });

    function getDates(startDate, endDate) {
      var dateArray = [];
      var currentDate = moment(startDate);
      var endDate = moment(endDate);
      while (currentDate <= endDate) {
        dateArray.push([moment(currentDate).format('dddd'), moment(currentDate).format('DD/MM/YYYY')])
        currentDate = moment(currentDate).add(1, 'days');
      }

      return dateArray;
    }
  </script>
<% end %>

app/views/assignments/_quotum_fields.html.erb
<div class='nested-fields'>
  <%= link_to_remove_association 'Remove quotum', f, class: 'badge badge-danger float-right' %>
  <div class="form-group">
    <%= f.label :q_hours, 'Hours' %>
    <%= f.number_field :q_hours, min: 0, max: 24, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :q_minutes, 'Minutes' %>
    <%= f.number_field :q_minutes, min: 0, max: 60, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, min: 0, class: 'form-control' %>
  </div>
</div>

app/views/assignments/_schedule_card.html.erb
<div class="col mb-4">
  <div class="card h-100 text-center">
    <div class="card-body">
      <h4 class="card-title"><%= date_formatter(schedule.scheduled_at) %></h4>
      <% schedule.quota.each do |quotum| %>
        <p class="card-text"><%= "<strong>Time:</strong> #{quotum.q_hours}:#{quotum.q_minutes.to_s.rjust(2, '0')}".html_safe %></p>
        <p class="card-text"><%= "<strong>Amount:</strong> #{quotum.amount}".html_safe %></p>
      <% end %>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= "Last updated at #{updated_at_formatter(schedule.updated_at)}" %></small>
    </div>
  </div>
</div>

app/views/assignments/_schedule_fields.html.erb
<div class='nested-fields'>
  <div class='row'>
    <div class="col">
      <div class="form-group">
        <%= f.label :scheduled_at %>
        <%= f.select :scheduled_at, f.object.assignment.options_for_select, { prompt: 'Select a day' }, { class: 'form-control' } %>
      </div>
    <%= link_to_remove_association "Remove schedule", f, class: 'btn btn-sm btn-danger' %>
    </div>
    <div class="col">
      <div class="quota">
        <%= f.fields_for :quota do |quota_form| %>
          <%= render 'quotum_fields', f: quota_form %>
        <% end %>
        <%= link_to_add_association 'Add quotum', f, :quota, class: 'btn btn-sm btn-dark float-right' %>
      </div>
    </div>
  </div>
</div>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>
<hr>

<%= render 'form', assignment: @assignment %>

app/views/assignments/index.html.erb
<h1>
  Assignments
  <%= link_to 'New Assignment', new_assignment_path, class: 'btn btn-primary float-right' %>
</h1>
<hr>

<div class="row row-cols-1 row-cols-md-3">
  <% @assignments.each do |assignment| %>
    <%= render 'card', assignment: assignment %>
  <% end %>
</div>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>
<hr>

<%= render 'form', assignment: @assignment %>

app/views/assignments/show.html.erb
<h1>
  <%= @assignment.name %>
  <%= link_to 'Back to Assignments', assignments_path, class: 'btn btn-primary float-right' %>
</h1>
<hr>

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-default">Start date</span>
  </div>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" disabled value="<%= date_formatter(@assignment.start_date) %>">
</div>

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-default">End date</span>
  </div>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" disabled value="<%= date_formatter(@assignment.end_date) %>">
</div>

<hr>

<h4>Schedules</h4>
<div class="row row-cols-1 row-cols-md-3">
  <% @assignment.schedules.each do |schedule| %>
    <%= render 'schedule_card', schedule: schedule %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'INNOVENCER', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item <%= controller_name == 'welcome' ? 'active' : '' %>">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= controller_name == 'assignments' ? 'active' : '' %>">
        <%= link_to 'Assignments', assignments_path, class: 'nav-link' %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <div class="my-2 my-lg-0">
        <a class="navbar-brand"><%= current_user.full_name %></a>
        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'btn btn-danger my-2 my-sm-0' %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Innovencer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container pt-20">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Bulk Dates Assignments</h1>
  <p class="lead">This is a simple web unit, basically to create a form where an user can create Schedules into a dates range.</p>
  <hr class="my-4">
  <p>This is a test for Innovencer.</p>
  <%= link_to 'Go to Assignments', assignments_path, class: 'btn btn-primary btn-lg' %>
</div>